### ISSUE TITLE
Some slides are missing

### ISSUE THREAD

**Issue by KunWang-22** [dcai-course/dcai-course#13]
Thank you for sharing such a wonderful course, I have benefited greatly. But I found that the slides of three lectures have not been uploaded so far, including Lecture 3: Dataset Creation and Curation, Lecture 5: Class Imbalance, Outliers, and Distribution Shift, and Lecture 9: Data Privacy and Security. I would be very grateful if you could upload them, thank you very much.

**Comment by anishathalye** [comment]
The slides aren't missing, these lectures were chalk talks. Lecture 3 has some slides at the beginning, those are just the Lecture 2 slides. Lecture 5 and Lecture 9 were 100% chalk talks. There are lecture notes and lecture videos, but no slides.
